name: 'ada-lint'
description: 'run ada-lint'
author: 'Trevor Bland (@trebland)'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
